basic_settings:
  site_title: Natalie Parde
  favicon_image: /images/favicon_io/favicon-32x32.png

header_settings:
  logo_image: 
  logo_width: 100

menu_settings:
  menu_items:
    - title: 'Research'
      url: 'research.html'
    - title: 'Team'
      url: 'team.html'
    - title: 'Publications'
      url: 'publications.html'
    - title: 'Teaching'
      url: 'teaching.html'
    - title: 'CV'
      url: {{ site.url }}'/cv.pdf'

footer_settings:
  logo_image: 
  logo_width: 100
  tagline: Natalie Parde's Personal Website

hero_settings:
  background_image: /images/backgrounds/scrabble_transparent_fade_border.png

post_settings:
  grid_spacing: 10

contact_settings:
  email_address:
  form_action:
  confirmation_url:
  email_subject:
  send_button_text:

social_settings:
  facebook_url: ''
  twitter_url: 'https://twitter.com/natalieparde'
  instagram_url: ''
  snapchat_url: ''
  youtube_url: 'https://www.youtube.com/channel/UCzz9P5QwGkRUesDpCOHMCOA'
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#202224'
  text_medium_color: '#6C7A89'
  text_light_color: '#AEB3BB'
  accent_color: '#900C3F'
  border_color: '#ECEDEF'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Abhaya+Libre&family=Lato" rel="stylesheet">'
  title_font: '"Abhaya Libre", serif'
  body_font: '"Lato", sans-serif'
  regular_weight: 400
  bold_weight: 700
  site_title:
    small_size: 30
    medium_size: 40
    large_size: 45
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 700
    letter_spacing: 0
  h1:
    size: 64
    size_small: 42
    weight: 700
    letter_spacing: -1.5
    letter_spacing_small: -1.2
    line_height: 72
    line_height_small: 48
  h2:
    size: 48
    size_small: 36
    weight: 700
    letter_spacing: -1.6
    letter_spacing_small: -1.04
    line_height: 56
    line_height_small: 44
  h3:
    size: 40
    size_small: 30
    weight: 700
    letter_spacing: -1.4
    letter_spacing_small: -0.54
    line_height: 48
    line_height_small: 36
  h4:
    size: 32
    size_small: 28
    weight: 700
    letter_spacing: -1
    letter_spacing_small: -0.6
    line_height: 36
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  subtitle:
    size: 22
    size_small: 20
    weight_regular: 400
    weight_heavy: 500
    letter_spacing: 0.16
    letter_spacing_small: 0.2
    line_height: 32
    line_height_small: 28
  p:
    size: 18
    size_small: 17
    weight: 400
    letter_spacing: 0.04
    letter_spacing_small: 0
    line_height: 28
  p_small:
    size: 16
    size_small: 15
    weight: 400
    letter_spacing: 0
    line_height: 24
  label:
    size: 14
    small_size: 12
    weight: 500
    letter_spacing: 0.8
    small_letter_spacing: 0.5
    line_height: 16
  footnote:
    size: 13
    weight: 400
    letter_spacing: -0.04
    line_height: 12
  blockquote:
    small_size: 22
    medium_size: 30
    large_size: 38
    weight: 500
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 500
    letter_spacing: 0.4

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
